version: 2

defaults: &defaults
  working_directory: ~/api-client-typescript-signalr
  docker:
    - image: circleci/node:8.9.1
jobs:
  deploy:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - restore_cache:
            keys:
            - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run: npm install
        - run: npm update
        - run: |
            if [ "${CIRCLE_BRANCH}" == 'master' ]; then
                npm update @flipdish/api-client-typescript@latest
            else
                npm update @flipdish/api-client-typescript@dev
            fi
        - run: npm prune
        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-
        - run: npm run build
        - run: rm -f api.ts 
        - run:
            name: Versioning
            command: npm version 1.0.0-dev.$CIRCLE_BUILD_NUM --no-git-tag-version
        - run:
            name: Version
            command: npm version
        - run:
            name: Publish package
            command: npm publish --access public --tag dev
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /^develop/
