version: 2

defaults: &defaults
  working_directory: ~/api-client-typescript-signalr
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run:
            name: Get dependencies
            command: npm install
        - run: npm prune
        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-

        - run: npm run build

        - persist_to_workspace:
            root: ~/api-client-typescript-signalr
            paths: .
  deploy:
    <<: *defaults
    steps:
        - attach_workspace:
            at: ~/api-client-typescript-signalr
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/api-client-typescript-signalr/.npmrc
        - run:
            name: Versioning
            command: npm version 1.0.$CIRCLE_BUILD_NUM --no-git-tag-version
        - run:
            name: Version
            command: npm version
        - run:
            name: Publish package
            command: npm publish --access public
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /^master/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^master/
