version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm prune
      - save_cache:
          key: npm-dependency-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
    - run: npm run build
    - run: npm version 1.0.$CIRCLE_BUILD_NUM --no-git-tag-version
    - run: npm version
    - run: npm publish --access public
    - store_artifacts:
        path: /tmp/circleci-artifacts
workflows:
  version: 2
  deploy:
    jobs:
        -deploy:
            requires:
                - build

